name: Update README

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Run update script
      run: |
        bash scripts/update_readme.sh
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
